project:
  type: website
  resources:
    - "_redirects"
  # render:
  #   - index.qmd
  #   - walking.qmd
    # - "blog/2017-02-17-portfolio-of-projects.md"
    # - "collection/Walking in Britain/*/*.*md"
    # - "!blog/2018-08-16-geotagging-voter-registrations/index.Rmd"
    # - section2.qmd
website:
  title: "Can I Blog Too?"
  site-url: "https://johngoldin.com/"
#  google-analytics: "UA-92008736-2"
  google-analytics:
    tracking-id: "G-3YW2GGXVXP"
    # setup at https://analytics.google.com/analytics/web/#/a92008736p353328788/admin/streams/table/4618471525
    # tracking-id: "UA-92008736-2"  is this the old id? stopped march 2023. new property id is 353328788
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: blog/apple-health-export/index.qmd
        text: Apple Health
      - href: projects.qmd
        text: Projects
      - href: walking.qmd
        text: UK Walking
      - href: about.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/johngoldin
        aria-label: John Goldin github
      - icon: twitter
        href: https://twitter.com/johngoldin
        aria-label: John Goldin Twitter
      - icon: mastodon
        href: https://mastodon.social/@johngoldin
        aria-label: <a rel="me" href="https://mastodon.social/@johngoldin">Mastodon</a>
      - icon: rss
        href: index.xml
      - text: Flickr
        href: https://www.flickr.com/people/99418994@N00/
        aria-label: John Goldin photos on Flickr
  favicon: favicon.png
  twitter-card: true
  open-graph: true
# possible themes: litera, lumen, spacelab
format:
  html:
    theme: spacelab
    comments:
      utterances:
        repo: johngoldin/can_i_blog_too
        # label: 'comments :crystal_ball:'
        # theme: boxy-light
        # use_utterances: yes
    css: styles.css
    toc: true
    footnotes-hover: true
    license: "CC BY-SA"

execute:
  freeze: auto

editor: visual




