baseURL = "https://johngoldin.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Can I Blog Too"
theme = "beautifulhugo"
metaDataFormat = "yaml"
footnotereturnlinkcontents = "↩"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
googleAnalytics = "UA-92008736-2"
gravatarHash = "f7dd8b52bc092b4e50e9324381b02d67"
disqusShortname = "johngoldin" # Optional, enable Disqus integration
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$",  "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
# next two lines suggested for seo by: https://keithpblog.org/post/hugo-website-seo/
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
    post = "/:year/:month/:slug/"
    
[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page 
	subtitle = "Some of my personal projects with R"
  mainSections = ["post","posts"]
  logo = "https://www.gravatar.com/avatar/f7dd8b52bc092b4e50e9324381b02d67?s=200"
#  logo = "img/avatar-icon.png" # Expecting square dimensions
#  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true 
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "John Goldin"
  website = "https://johngoldin.com/"
  email = "john.r.goldin@gmail.com"
  github = "johngoldin"
  twitter = "johngoldin"
  flickr = "99418994@N00"
    # add code below to themes/beautifulhugo/data/beautifulhugo/social.toml
    # [[social_icons]]
    # id = "flickr"
    # url = "https://www.flickr.com/people/%s"
    # title = "Flickr"
    # icon = "fab fa-flickr"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

#[[menu.main]]
#    identifier = "samples"
#   name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
