baseURL = "https://distracted-swanson-8d1a85.netlify.com/"
languageCode = "en-us"
title = "Can I Blog Too"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

paginate = 10
license = "https://opensource.org/licenses/MIT"
sidebar = "right"
disqusShortname = "johngoldin"

[author]
    name = "John Goldin"
[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/johngoldin"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/johngoldin"
[[menu.main]]
    name = "Flickr"
    url = "https://www.flickr.com/photos/99418994@N00/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
[params]
    description = "Some of my personal projects with R"
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Your default page description"
    defaultKeywords = "your,default,page,keywords"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Notes on this and that..."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-92008736-1"
    gravatarHash = "f7dd8b52bc092b4e50e9324381b02d67"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"
    
    # Sidebar social links, these must be full URLs.
    github = ""
    bitbucket = ""
    stackOverflow = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

